### ISSUE TITLE
Tests failing on node >= v0.11

### ISSUE THREAD

**Issue by mpreziuso** [brycebaril/timestream-aggregates#1]
Hello,

we've some got problems under node v0.11.14.

`Cannot read property 'v' of undefined`

```
[root@localhost timestream-aggregates]# npm test

> timestream-aggregates@0.1.5 test /tmp/timestream-aggregates
> node test/

TAP version 13
# init
ok 1 sum is a function
ok 2 mean is a function
ok 3 median is a function
ok 4 mode is a function
ok 5 variance is a function
ok 6 stdev is a function
ok 7 percentile is a function
ok 8 min is a function
ok 9 max is a function
ok 10 first is a function
ok 11 last is a function
ok 12 count is a function
ok 13 sample is a function
# sum entire series
ok 14 Got expected results
# sum entire series (with timestamp)
not ok 15 Got expected results
  ---
    operator: deepEqual
    expected: [{"_t":1378450800000,"gen":55}]
    actual:   [{"_t":1378425600000,"gen":55}]
    at: check (/tmp/timestream-aggregates/test/index.js:46:7)
  ...
 # sum multi column
 /tmp/timestream-aggregates/node_modules/tape/index.js:65
     throw err
             ^
TypeError: Cannot read property 'v' of undefined
    at Transform.slot [as _transform] (/tmp/timestream-aggregates/factory.js:42:35)
    at Transform._read (/tmp/timestream-aggregates/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/tmp/timestream-aggregates/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/tmp/timestream-aggregates/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/tmp/timestream-aggregates/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/tmp/timestream-aggregates/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Spigot.ondata (_stream_readable.js:539:20)
    at Spigot.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:162:16)
    at Spigot.Readable.push (_stream_readable.js:125:10)
npm ERR! Test failed.  See above for more details.
```

**Comment by brycebaril** [comment]
Confirmed, investigating...

**Comment by brycebaril** [comment]
Something is broken with http://npm.im/stream-spigot that might be the culprit here. Filed an issue for it there (also my library) https://github.com/brycebaril/node-stream-spigot/issues/3

**Comment by mpreziuso** [comment]
Great, thanks :)

**Comment by brycebaril** [comment]
Ok, please try again -- pull down the latest and npm install to update the dependencies.

**Comment by mpreziuso** [comment]
Great work! Fixed.
